import "dotenv/config";
import { and, eq } from "drizzle-orm";
import { db } from "../src/db";
import {
  budgets,
  dayLogs,
  monthlyReports,
  monthSettings,
  projects,
  timeEntries,
  users,
  workTypes,
} from "../src/db/schema";
import { ymd } from "../src/lib/dates";

async function main() {
  const year = new Date().getFullYear();
  const month = new Date().getMonth() + 1;

  const projectRows = await db.select().from(projects).limit(4);
  const workTypeRows = await db.select().from(workTypes).limit(6);
  const memberRows = await db.select().from(users).where(eq(users.role, "MEMBER")).limit(10);

  if (!projectRows.length || !workTypeRows.length) {
    console.error("Không tìm thấy project hoặc work type. Hãy chạy seed trước bằng: npm run db:seed");
    process.exit(1);
  }

  if (!memberRows.length) {
    console.error("Không tìm thấy member. Hãy chạy seed trước bằng: npm run db:seed");
    process.exit(1);
  }

  const adminRow = await db.select().from(users).where(eq(users.role, "ADMIN")).limit(1);
  const adminId = adminRow[0]?.id ?? memberRows[0].id;

  await db.insert(monthSettings)
    .values({ year, month, workingDays: 22 })
    .onConflictDoUpdate({
      target: [monthSettings.year, monthSettings.month],
      set: { workingDays: 22, lockedAt: null },
    });

  for (const user of memberRows) {
    for (const project of projectRows) {
      await db.insert(budgets)
        .values({
          userId: user.id,
          projectId: project.id,
          year,
          month,
          hours: "20.00",
        })
        .onConflictDoUpdate({
          target: [budgets.userId, budgets.projectId, budgets.year, budgets.month],
          set: { hours: "20.00", updatedAt: new Date() },
        });
    }

    const dates = [1, 2, 3, 4, 5, 6, 7, 8];
    for (const day of dates) {
      const date = ymd(year, month, day);
      const startMin = 9 * 60;
      const endMin = 18 * 60;
      const breakMin = 60;

      await db.insert(dayLogs)
        .values({
          userId: user.id,
          date,
          startMin,
          endMin,
          breakMin,
          dayType: "WORK",
          leaveNote: null,
          remark: "Seed demo data",
        })
        .onConflictDoUpdate({
          target: [dayLogs.userId, dayLogs.date],
          set: {
            startMin,
            endMin,
            breakMin,
            dayType: "WORK",
            leaveNote: null,
            remark: "Seed demo data",
            updatedAt: new Date(),
          },
        });

      await db.delete(timeEntries).where(and(eq(timeEntries.userId, user.id), eq(timeEntries.date, date)));

      const entries = [
        { projectId: projectRows[0].id, workTypeId: workTypeRows[0].id, hours: "3.5", description: "Requirement analysis" },
        { projectId: projectRows[1 % projectRows.length].id, workTypeId: workTypeRows[1 % workTypeRows.length].id, hours: "2.5", description: "Coding" },
        { projectId: projectRows[2 % projectRows.length].id, workTypeId: workTypeRows[2 % workTypeRows.length].id, hours: "2.0", description: "Testing" },
      ];

      await db.insert(timeEntries).values(
        entries.map((item) => ({
          userId: user.id,
          date,
          projectId: item.projectId,
          workTypeId: item.workTypeId,
          description: item.description,
          hours: item.hours,
          isPlan: false,
        })),
      );
    }

    await db.insert(monthlyReports)
      .values({
        userId: user.id,
        year,
        month,
        status: "APPROVED",
        reviewedAt: new Date(),
        reviewerId: adminId,
        reviewNote: "Demo seed for export testing",
        memberNote: "Generated by seed-timesheet-demo",
      })
      .onConflictDoUpdate({
        target: [monthlyReports.userId, monthlyReports.year, monthlyReports.month],
        set: {
          status: "APPROVED",
          reviewedAt: new Date(),
          reviewerId: adminId,
          reviewNote: "Demo seed for export testing",
          memberNote: "Generated by seed-timesheet-demo",
          updatedAt: new Date(),
        },
      });
  }

  console.log(`Seeded demo month data for ${memberRows.length} members in ${year}-${String(month).padStart(2, "0")}`);
  console.log("You can now test export / admin approval / Excel generation.");
  process.exit(0);
}

main().catch((error) => {
  console.error("seed-timesheet-demo failed:");
  console.error(error);
  process.exit(1);
});
